add pytest junit report pylint.yml

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -11,6 +11,9 @@ jobs:
   test:
     runs-on: ubuntu-latest
 
+    permissions:
+      checks: write
+
     steps:
     - name: Checkout repository
       uses: actions/checkout@v2
@@ -34,7 +37,13 @@ jobs:
       env:
           API_KEY: ${{ secrets.API_KEY }}
       run: | 
-        pytest --junit-xml=test-results.xml
+        python -m pytest --verbose --junit-xml=test-results.xml
+        
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/junit.xml'
         
     - name: Run Pylint on the entire project
       run: pylint $(git ls-files '*.py')
