trick 5, actions logger

diff --git a/.github/workflows/pylint.yml b/.github/workflows/pylint.yml
--- a/.github/workflows/pylint.yml
+++ b/.github/workflows/pylint.yml
@@ -1,34 +1,59 @@
-name: Appium Tests
+name: Lint and Test
 
-on: [push]
-
-jobs:
-  appium-tests:
-    runs-on: ubuntu-latest
+on:
+  push:
+    branches:
+      - main
+  schedule:
+    - cron: "0 0 * * *"
     
+jobs:
+  test:
+    runs-on: ubuntu-latest
+
+    permissions:
+      checks: write
+
     steps:
-    - name: Checkout code
+    - name: Checkout repository
       uses: actions/checkout@v2
-      
+
     - name: Set up Python
       uses: actions/setup-python@v2
       with:
         python-version: 3.8
-      
+
+    - name: Use Node.js 16.x
+      uses: actions/setup-node@v2
+      with:
+        node-version: 16.x
+
+    - name: Install Appium
+      run: |
+        npm install -g appium
+        appium --version
+        appium &>dev/null &
+
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt  # Adjust to your requirements file name
-      
-    - name: Start Appium Server
-      run: |
-        npm install -g appium
-        appium &
-      
-    - name: Run Appium Tests
-      run: |
-        pytest tests/  # Adjust to your test directory
-      
-    - name: Stop Appium Server
-      run: |
-        pkill -f appium
+        pip install -r requirements.txt
+
+    - name: Run pytest
+      env:
+          API_KEY: ${{ secrets.API_KEY }}
+      run: | 
+        python -m pytest --verbose --junit-xml=test-results.xml
+        
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v3
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/test-results.xml'
+        detailed_summary: true
+        include_passed: true
+        
+    - name: Run Pylint on the entire project
+      run: pylint $(git ls-files '*.py')
+      env:
+        PYLINTRC: dev
